### ISSUE TITLE
Module stopped working

### ISSUE THREAD

**Issue by ihadx** [CFenner/MMM-Netatmo#158]
I'm pretty sure that Netatmo has finally depricated "Client credentials grant type" in favour of "Authorization code grant type".
Go to https://dev.netatmo.com/apidocumentation/oauth and look for 'Client credentials grant type'

Is someone in the community skilled enough to upgrade the existing code?

**Comment by Laz2516** [comment]
I join the request! (((
I also stopped working the module, after about June 29.... (((

**Comment by CFenner** [comment]
Will try to setup MM again to fix this. Any more hints for me? Are you willing to test the changes?

**Comment by skyhawk180** [comment]
> Will try to setup MM again to fix this. Any more hints for me? Are you willing to test the changes?

I'll be glad to test the changes as well. I believe the oauth2 auth code changes are described here: https://dev.netatmo.com/apidocumentation/oauth#authorization-code. Standing by.

**Comment by Laz2516** [comment]
I am also ready to help if I understand how to get a new authorization (token probably).

**Comment by Laz2516** [comment]
Maybe this will help the developer fix the authorization?.....

https://forum.netatmo.com/viewtopic.php?t=21383

**Comment by Laz2516** [comment]
https://forum.magicmirror.builders/topic/12315/mmm-netatmo-updated/42?page=5

Could help the developer....
How you can get tokens.
The module from RaymondMolenaar works after retrieving the authorization data again on the Netatmo website.

**Comment by Laz2516** [comment]
Authorization also stopped working in the RainMachine application. This solution appeared on the user forum. Perhaps this will help a respected developer.
I cite links....

Change: https://github.com/zagy/rainmachine-developer-resources/commit/df1d75b84cf9fb12b3334029c48e5cbf6b8625d0

File: https://raw.githubusercontent.com/zagy/rainmachine-developer-resources/df1d75b84cf9fb12b3334029c48e5cbf6b8625d0/sdk-parsers/RMParserFramework/parsers/personalnetatmo-parser.py (can be uploaded via the rainmachine UI)

It's not very tested, but seems to work for now.

**Comment by Laz2516** [comment]
The token can be obtained from the Netatmo app. Where are the keys.
![image](https://github.com/CFenner/MMM-Netatmo/assets/40304797/ad8a3802-4ed8-4ef0-b44f-d980f81ae228)

**Comment by CFenner** [comment]
@Laz2516 @skyhawk180 @ihadx Can you check if this works for you?

https://github.com/CFenner/MMM-Netatmo/pull/182

**Comment by Laz2516** [comment]
Of course. I will check now.))

**Comment by Laz2516** [comment]
Unfortunately, it doesn't work. Module icons do not appear on the screen.
I deleted only my login and password. He left the keys. And added a refresh token. Right?
Raspberry overloaded.  
Perhaps in the Personal Account-Settings-Partner Applications you need to remove the permission for the old MagicMirror?

"
{
			module: 'netatmo',
			position: 'top_left', // the location where the module should be displayed
			header: 'ДОМАШНЯЯ МЕТЕОСТАНЦИЯ', // a header if you like one
			config: {
				clientId: '63319aa6d7d9ebХХХХХХХХХ', // your app id
				clientSecret: 'ХХХХХBeNDqyerfjkZaХХХХХХХХХХХ', // your app secret
				refresh_token: 'ХХХХХХХХ75368c04c4188c8b52cf|0e864b8ХХХХХХХХХХХХХХ',
				// username: 'ХХХХХХХХ', // your netatmo username
				// password: 'ХХХХХХХХХ', // your netatmo password
				// moduleOrder: ["NAMain", "NAModule4", "NAModule1", "NAModule3", "NAModule2" ],
			}
		},

![image](https://github.com/CFenner/MMM-Netatmo/assets/40304797/c36ebfc5-7531-4bcb-92d5-81edebc7eb0f)

**Comment by Laz2516** [comment]
refresh_token: 'ХХХХХХХХХХХХХХХХХХХХ88c8b52cf|0e864b8f9ХХХХХХХХХХХХХХ',
access_token: 'ХХХХХХХХХХХХХХХХХХХХХХcf|d8d36de50b9c7ХХХХХХХХХХХХХХ',

Alas, adding an access token to the configuration did not help. The weather station does not show the data....

**Comment by CFenner** [comment]
> I deleted only my login and password. He left the keys. And added a refresh token. Right?

Did you update the module code from the auth branch?

**Comment by Laz2516** [comment]
No.... ((
Can I completely download the module again in the zip file and expand the archive on top of the old module?)

**Comment by Laz2516** [comment]
I downloaded the archive, uploaded it to raspberries. And replaced all the files that were fresh. But there are no files in the archive
helper.js
helper.test.js
module.js

**Comment by CFenner** [comment]
Please use this archive https://github.com/CFenner/MMM-Netatmo/archive/refs/heads/auth.zip

**Comment by Laz2516** [comment]
Downloaded your archive from the link. Replaced only new files. After rebooting the raspberry, the MM program itself does not start. I see only a raspberry desktop.
Then I wrote completely all the files from your archive on top of the installed module.
The same thing, I see only the desktop, MM does not start....

**Comment by Laz2516** [comment]
Returned the old module completely from the copy, MM starts.

**Comment by CFenner** [comment]
Ok, then I'm need to run the module myself. Sorry for the inconvenience.

**Comment by Laz2516** [comment]
Good. Then I am waiting for your decision.
A separate archive with only modified files would be good. To avoid spoiling module settings.

And I would very much like, since you have taken up the module, to be able to display the pressure value in mm Hg.

**Comment by CFenner** [comment]
It actually works for me, I just missed to run `npm clean-install --production --ignore-scripts` as stated in the instructions.

**Comment by CFenner** [comment]
So changes are merged to main branch. You need to
- load the latest code via file (https://github.com/CFenner/MMM-Netatmo/archive/refs/heads/main.zip) or git clone
- run `npm ci --production --ignore-scripts` inside the module folder
- remove username/password and add refresh_token to config

**Comment by Laz2516** [comment]
Good afternoon!
Performed your actions.
Deleted the module, wrote the contents of the archive to the module folder. Executed a command inside the module folder.
MM starts (I have a previous version, not 2.4), but only the clock is loaded from the modules. All other modules in the "Download" state

**Comment by CFenner** [comment]
Which version could that be?

**Comment by Laz2516** [comment]
Last before 2.4
If you tell me how to find out the version number, I will look more accurately. Unfortunately, I am not a strong specialist in raspberries. I can only repeat according to the written... ((

**Comment by Laz2516** [comment]
If I temporarily rename the netatmo folder, for example, to netatmo1 and restart the raspberry, then MM starts and all modules start.

**Comment by CFenner** [comment]
@skyhawk180 
> Not sure the code is correctly loaded/committed into git. I see differences in netatmo files between branches and also helper files. I am sure I'm missing something that you have a local copy of. Can you just zip your working copy of netatmo folder (under MM/modules) and provide me and I can see if that runs. If so, we can compare code base with git. I have the latest MM 2.4 and node/npm and all other modules are working if I remove this folder.

If you download the current main branch content, there is a `compose` folder with instructions how to run locally in a MM docker container. Would that help?

**Comment by Laz2516** [comment]
> Какая это может быть версия?

Please help figure out why the MM does not start if you install your modified module...? ((((((((

**Comment by Laz2516** [comment]
Probably in vain closed the problem....

**Comment by CFenner** [comment]
On vacation for the next days, can look into it next week.

**Comment by Laz2516** [comment]
Have a great holiday!!
(we hope that you can defeat Netatmo authorization!!))))

**Comment by CFenner** [comment]
@skyhawk180 @Laz2516 what does the [browser console](https://screenful.com/guide/how-to/how-to-open-the-browser-developer-console#) show? There should be an error message.

**Comment by Laz2516** [comment]
> @skyhawk180 @Laz2516что показывает [консоль браузера](https://screenful.com/guide/how-to/how-to-open-the-browser-developer-console#) ? Должно появиться сообщение об ошибке.

Unfortunately, I am not very well versed in programming. I can only repeat the tips. Tell me how to see the error?
At the moment, with the latest version of the module (I wrote about this above), MM does not start completely. Only two modules are launched, the rest in the "Download" status. If you change the name of the netatmo module to netatmo1, so that the module does not start from the config, then the MM starts normally, all the modules that I use.

**Comment by CFenner** [comment]
Did you connect to your MM on the RPi with the Firefox or was MM running on your machine?
So is the error when displaying it with electron or on the RPi in general?

**Comment by eierfeile** [comment]
I also have the same issue. But it sounds the latest version of netatmo module isnt the final solution. Is it mandatory to have latest version of magirmirrorOS installed to make the module run properly?

**Comment by Laz2516** [comment]
Unfortunately, for some reason we are not enough in this topic. Is Netatmo station in MM really so little used?
Maybe one of us should give access to the author of the module to his station so that the author can check the module improvements himself?

**Comment by Laz2516** [comment]
https://support.rainmachine.com/hc/en-us/articles/13251844688151-NetAtmo-Weather-Service-2023-Update-Fix-

That may help you.
This developer of the auto-watering system has changed its module to access Netatmo.

**Comment by torth** [comment]
hi folks, I read your instructions and I can agree - problem is still existing.

I generated a new App in dev.netatmo.com
generated a "read_station" Token
mv netatmo -> netatmo_old
git clone https://github.com/CFenner/MMM-Netatmo.git netatmo
npm ci --production --ignore-scripts
reconfigured config.js with clientId: '',  clientSecret: '',  refresh_token: '', 

but ... after pm2 restart are all modules in state "Downloading" and showing no data

once I deactivated 'netamo' in my config the MM runs as expected and correctly. When 'netatmo' config is enabled I'm also not able to access MM remote with browser <local_ip>:8080 

don't know how to help / assist, but I'll you support as much as I can.

**Comment by Laz2516** [comment]
> Привет, ребята, я прочитал ваши инструкции и могу согласиться - проблема все еще существует.
> 
> Я создал новое приложение на dev.netatmo.com, сгенерировал токен «read_station» mv netatmo -> netatmo_old git clone https://github.com/CFenner/MMM-Netatmo.git netatmo npm ci --production --ignore-scripts перенастроил config.js с clientId: '', clientSecret: '',refresh_token: '',
> 
> но... после перезапуска pm2 все модули находятся в состоянии «Загрузка» и не отображают никаких данных
> 
> как только я деактивировал «netamo» в своей конфигурации, ММ работает как положено и правильно. Когда включена конфигурация «netatmo», я также не могу получить удаленный доступ к MM с помощью браузера <local_ip>:8080.
> 
> не знаю чем помочь/содействовать, но поддержу, чем смогу.

I also have the same, one in one

**Comment by Laz2516** [comment]
> но с модулем RaymondMolenaar Netatmo и моими новыми учетными данными все работает,

I would not like to change the module. I'm quite fine with this one. If I can then change the pressure display format. And perhaps now there are errors in the display of the wind, but I have a faulty wind sensor itself, I bought a new one. Then I will write comments.

**Comment by Laz2516** [comment]
> Попробую снова настроить MM, чтобы это исправить. Есть еще подсказки для меня? Готовы ли вы протестировать изменения?

Did you manage to change something in the module for Netatmo authorization? I wrote you a sentence and links above.
I can give access to my station for your experiments. If it doesn't work out differently.....

**Comment by CFenner** [comment]
> I can give access to my station for your experiments. If it doesn't work out differently.....


That's a great idea. 

My mail would be Christopher.fenner@me.com

**Comment by fradrik** [comment]
please update this thread if you find a solution. I have been following here since june, because my netatmo-module in MM is not working either. Thanks. :)

**Comment by Laz2516** [comment]
> > Могу предоставить доступ к моей станции для ваших экспериментов. Если не получится по-другому.....
> 
> Это блестящая идея.
> 
> Моя почта будет [Christopher.fenner@me.com.](mailto:Christopher.fenner@me.com)

Sent you the data.

**Comment by Laz2516** [comment]
> > Могу предоставить доступ к моей станции для ваших экспериментов. Если не получится по-другому.....
> 
> Это блестящая идея.
> 
> Моя почта будет...

Do you have Telegrams? I can't insert the archive into my mail.

**Comment by Laz2516** [comment]
Thank you, sent the archive.

**Comment by Laz2516** [comment]
The developer of the module is still busy. With my data, he managed to authorize and display information from the Netatmo station in the MM.
We are waiting for the module correction....)

**Comment by Laz2516** [comment]
Authorization data is not valid?
But they didn't change.

I have a RainMachine auto-watering controller. It also uses data from the weather station Netatmo. And since June, the controller could not connect to the cloud of the weather station using the old authorization method. A couple of weeks ago, technical support changed the software connection module. There I use exactly the same data and everything works.

If you are talking about my archive with your module, then check the authorization data in the config. Which I sent you in a letter. Perhaps in the config just actually old data. Fix them.

**Comment by Laz2516** [comment]
> @Laz2516 you credentials are no longer valid. Unfortunately the module does not yet bring this to the frontend.
> 
> ```
> mm  | [14.09.2023 14:55.17.314] [LOG]   error: Error: invalid_grant: undefined
> mm  |     at Class.authenticate (/opt/magic_mirror/modules/netatmo/helper.js:41:15)
> mm  |     at Class.socketNotificationReceived (/opt/magic_mirror/modules/netatmo/helper.js:125:14)
> mm  |     at Socket.<anonymous> (/opt/magic_mirror/js/node_helper.js:107:11)
> mm  |     at Socket.emit (node:events:513:28)
> mm  |     at Socket.emitUntyped (/opt/magic_mirror/node_modules/socket.io/dist/typed-events.js:69:22)
> mm  |     at /opt/magic_mirror/node_modules/socket.io/dist/socket.js:703:39
> mm  |     at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
> ```

Authorization data is not valid?
But they didn't change.

I have a RainMachine auto-watering controller. It also uses data from the weather station Netatmo. And since June, the controller could not connect to the cloud of the weather station using the old authorization method. A couple of weeks ago, technical support changed the software connection module. There I use exactly the same data and everything works.

If you are talking about my archive with your module, then check the authorization data in the config. Which I sent you in a letter. Perhaps in the config just actually old data. Fix them.

**Comment by Laz2516** [comment]
Good afternoon!
Can I help you with checking your module? I would like it to work faster..)))

**Comment by Laz2516** [comment]
Good afternoon!
Have you completely forgotten about us?))))

**Comment by Laz2516** [comment]
Good afternoon!
I've formed all the new data again.
But the module does not load... (((

Try at home...... I sent you my config in telegrams

**Comment by Laz2516** [comment]
I have updated to 2.25, but the module does not start and does not allow the rest of the modules to start...
If you rename the module folder or return the module archive before you change (in August), then the mirror with all modules starts, except for the Netatmo module.
Unfortunately, I can't see the bugs in the browser console.
Anyone tell me how to do this?

**Comment by fradrik** [comment]
@Laz2516 I [found this](https://forum.magicmirror.builders/topic/18112/mmm-netatmo-does-not-load/2). Tommys's solution worked for me as well.
I had to rename the "ModuleOrder" in config.js so it matches the productes names in the Netatmo App.

**Comment by Laz2516** [comment]
> @Laz2516Я [нашел это](https://forum.magicmirror.builders/topic/18112/mmm-netatmo-does-not-load/2) . Решение Томмиса сработало и для меня. Мне пришлось переименовать «ModuleOrder» в config.js, чтобы он соответствовал именам продуктов в приложении Netatmo.

I tried it, but it doesn't work. It is possible that I have module names in Russian in the Netatmo application...
And you have this module of the old version or already changed by the author (I think it may be for me to reinstall the module).

**Comment by cgillinger** [comment]
There is a guy in this thread who appears to have solved it. Unfortunately Im not code-savvy enough to implement it:

https://forum.magicmirror.builders/topic/18112/mmm-netatmo-does-not-load/5

**Comment by y0m1g** [comment]
I was getting `Error: invalid_grant : undefined`, tried updating my the refresh token, even client ID and client secret, didn't work... after some investigation I ended deleting the `token.json` file, and it worked again after a restart!
